### PR TITLE
MAG-1386 Removed all the events from the documentation

### PR DESCRIPTION
**Pull request by vavas**
- Removed all the events from the documentation

Please review:
@excelWithBusiness/developers 

**JERA Card**
https://filtered-ewb.atlassian.net/browse/MAG-1386

### CODE REVIEW

**Comment by vavas** [comment]
retest this please

**Comment by tricaalexandru** [comment]
retest this please

**Comment by tricaalexandru** [comment]
retest this please

**Comment by tricaalexandru** [comment]
@vavas please remove the - event as well not just the list. That endpoint should no longer be exposable in V2.

**Pull request merged**
