### PR TITLE
MAG-1144 updated documentation for user.Refresh method

### PR DESCRIPTION
**Pull request by vavas**
-  Updated documentation for user.Refresh method

@excelWithBusiness/developers

### CODE REVIEW

**Comment by vavas** [comment]
Screenshot from 2019-06-07 15-13-30

**Comment by tricaalexandru** [comment]
@vavas one small thing. It should be in its own token section. It's not a user function anymore.

**Comment by vavas** [comment]
Screenshot from 2019-06-07 16-21-56

**Comment by aaronkrohn** [comment]
how the hell do i still have access lol

**Comment by vavas** [comment]
@aaronkrohn hey Man! we keep you updated :)

**Comment by tricaalexandru** [comment]
@aaronkrohn wow :))) :))))

**Comment by aaronkrohn** [comment]
@tricaalexandru looking good guys!!!

**Comment by vavas** [comment]
Screenshot from 2019-06-12 18-11-02

**Comment by vavas** [comment]
@tricaalexandru please re-review

**Pull request merged**
